name: Build & Deploy APK

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Verify Files
        run: ls -la  # Debugging step to check if package.json exists

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "❌ ERROR: package.json not found!"
            exit 1
          fi

      - name: Log in to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: expo login --token $EXPO_TOKEN

      - name: Build APK
        run: expo build:android -t apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: banking-app-apk
          path: dist/*.apk
