name: Build & Deploy APK

on:
  push:
    branches:
      - main  # בכל דחיפה ל-main תתבצע בניית APK

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Install dependencies
        run: npm install

      - name: Log in to Expo
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: expo login --token $EXPO_TOKEN

      - name: Build APK
        run: expo build:android -t apk

   - name: Upload APK artifact
  uses: actions/upload-artifact@v4  
  with:
    name: banking-app-apk
    path: dist/*.apk
